Update tests
Signed-off-by: Jeffrey H. Johnson <trnsz@pobox.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -2715,8 +2715,7 @@ Linux/x86_64 (uClibc-ng, G++, GCC):
 
 ##############################################################################
 
-# Disabled due to crash in format-std-iostream test
-.Linux/x86_64 (Circle C++, GCC):
+Linux/x86_64 (Circle C++, GCC):
   stage: build
   tags:
     - Docker-x64
@@ -2789,9 +2788,9 @@ Node.js/WebAssembly (Emscripten, Em++, Emcc):
     - |
       # Start of Test ...
       echo -e "section_start:`date +%s`:Test_section[collapsed=true]\r\e[0K\033[0;36mTest ...\033[0m" || true
-    - node build/bin/sirexample; echo Exit $?
-    - ( set -e ; node build/bin/sirtests --list | grep "$(printf '\t')" | tr "$(printf '\t')" "\n" | tr -d " $(printf '\t')" | grep -Ev '(^$|^filesystem$|^performance$)' | xargs -I{} sh -c "set -e;node build/bin/sirtests --only {};echo Exit $?" ); echo Exit $?
-    - node build/bin/sirtests++; echo Exit $?
+    - node build/bin/sirexample
+    - ( set +e ; node build/bin/sirtests --list | grep "$(printf '\t')" | tr "$(printf '\t')" "\n" | tr -d " $(printf '\t')" | grep -Ev '(^$|^filesystem$|^performance$)' | xargs -I{} sh -c "set +e; node build/bin/sirtests --only {} || { printf '\n%s\n' "TEST FAILURE" ) | grep -q "^TEST FAILURE$" && exit 1; true
+    - node build/bin/sirtests++
     - |
       # End of Test ...
       echo -e "section_end:`date +%s`:Test_section\r\e[0K" || true
@@ -2837,9 +2836,9 @@ Node.js/JavaScript (Emscripten, Em++, Emcc):
     - |
       # Start of Test ...
       echo -e "section_start:`date +%s`:Test_section[collapsed=true]\r\e[0K\033[0;36mTest ...\033[0m" || true
-    - node build/bin/sirexample; echo Exit $?
-    - ( set -e ; node build/bin/sirtests --list | grep "$(printf '\t')" | tr "$(printf '\t')" "\n" | tr -d " $(printf '\t')" | grep -Ev '(^$|^filesystem$|^performance$)' | xargs -I{} sh -c "set -e;node build/bin/sirtests --only {};echo Exit $?" ); echo Exit $?
-    - node build/bin/sirtests++; echo Exit $?
+    - node build/bin/sirexample
+    - ( set +e ; node build/bin/sirtests --list | grep "$(printf '\t')" | tr "$(printf '\t')" "\n" | tr -d " $(printf '\t')" | grep -Ev '(^$|^filesystem$|^performance$)' | xargs -I{} sh -c "set +e; node build/bin/sirtests --only {} || { printf '\n%s\n' "TEST FAILURE" ) | grep -q "^TEST FAILURE$" && exit 1; true
+    - node build/bin/sirtests++
     - |
       # End of Test ...
       echo -e "section_end:`date +%s`:Test_section\r\e[0K" || true
