Split tests
Signed-off-by: Jeffrey H. Johnson <trnsz@pobox.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -3149,7 +3149,7 @@ DUMA:
 
 ################################################################################
 
-OpenOSC (GCC):
+OpenOSC (MM=1, GCC):
   stage: lint_dynamic
   needs:
     - job: Style check
@@ -3184,15 +3184,81 @@ OpenOSC (GCC):
       # End of OpenOSC GCC MM=1 test ...
       echo -e "section_end:`date +%s`:openosc_gcc1test_section\r\e[0K" || true
     - *CheckLogRemnants
+  dependencies: []
+  artifacts:
+    when: always
+    expire_in: 7 days
+    paths:
+      - build/
+      - logs/
+  retry: 2
+  interruptible: true
+
+################################################################################
+
+OpenOSC (MM=1, Clang):
+  stage: lint_dynamic
+  needs:
+    - job: Style check
+  tags:
+    - Docker-x64
+    - Linux
+  image:
+    name: registry.gitlab.com/libsir/libsir/openosc:latest
+  script:
+    - *Configuration
+    - |
+      # Start of OpenOSC Clang MM=1 build ...
+      echo -e "section_start:`date +%s`:openosc_clang1_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=1 build ...\033[0m" || true
+    - export CC="clang"
+    - export CXX="clang++"
+    - export CFLAGS="-DOPENOSC_MM=1"
+    - ${CC:?} --version
+    - ${CXX:?} --version
+    - make OPENOSC=1
+    - make tests++ OPENOSC=1
+    - |
+      # End of OpenOSC Clang MM=1 build ...
+      echo -e "section_end:`date +%s`:openosc_clang1_section\r\e[0K" || true
+    - *BuildInformation
     - |
       # Start of cleanup ...
-      echo -e "section_start:`date +%s`:openosc_clean_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC cleanup ...\033[0m" || true
-    - make distclean
+      echo -e "section_start:`date +%s`:openosc_clean_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=1 cleanup ...\033[0m" || true
     - |
-      # End of cleanup ...
-      echo -e "section_end:`date +%s`:openosc_clean_section\r\e[0K" || true
+      # Start of OpenOSC Clang MM=1 test ...
+      echo -e "section_start:`date +%s`:openosc_clang1test_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=1 Test ...\033[0m" || true
+    - stdbuf -o L ./build/bin/sirexample
+    - stdbuf -o L ./build/bin/sirtests
+    - stdbuf -o L ./build/bin/sirtests++
     - |
-      # Start of OpenOSC MM=2 GCC build ...
+      # End of OpenOSC Clang MM=1 test ...
+      echo -e "section_end:`date +%s`:openosc_clang1test_section\r\e[0K" || true
+    - *CheckLogRemnants
+  dependencies: []
+  artifacts:
+    when: always
+    expire_in: 7 days
+    paths:
+      - build/
+      - logs/
+  retry: 2
+  interruptible: true
+
+################################################################################
+
+OpenOSC (MM=2, GCC):
+  stage: lint_dynamic
+  needs:
+    - job: Style check
+  tags:
+    - Docker-x64
+    - Linux
+  image:
+    name: registry.gitlab.com/libsir/libsir/openosc:latest
+  script:
+    - *Configuration
+    - |
+      # Start of OpenOSC GCC MM=2 build ...
       echo -e "section_start:`date +%s`:openosc_gcc2_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC GCC MM=2 build ...\033[0m" || true
     - export CC="gcc"
     - export CXX="g++"
@@ -3204,6 +3270,7 @@ OpenOSC (GCC):
     - |
       # End of OpenOSC GCC MM=2 build ...
       echo -e "section_end:`date +%s`:openosc_gcc2_section\r\e[0K" || true
+    - *BuildInformation
     - |
       # Start of OpenOSC GCC MM=2 test ...
       echo -e "section_start:`date +%s`:openosc_gcc2test_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC GCC MM=2 test ...\033[0m" || true
@@ -3226,7 +3293,7 @@ OpenOSC (GCC):
 
 ################################################################################
 
-OpenOSC (Clang):
+OpenOSC (MM=2, Clang):
   stage: lint_dynamic
   needs:
     - job: Style check
@@ -3238,39 +3305,8 @@ OpenOSC (Clang):
   script:
     - *Configuration
     - |
-      # Start of OpenOSC Clang MM=1 build ...
-      echo -e "section_start:`date +%s`:openosc_Clang1_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=1 build ...\033[0m" || true
-    - export CC="clang"
-    - export CXX="clang++"
-    - export CFLAGS="-DOPENOSC_MM=1"
-    - ${CC:?} --version
-    - ${CXX:?} --version
-    - make OPENOSC=1
-    - make tests++ OPENOSC=1
-    - |
-      # End of OpenOSC Clang MM=1 build ...
-      echo -e "section_end:`date +%s`:openosc_Clang1_section\r\e[0K" || true
-    - *BuildInformation
-    - |
-      # Start of cleanup ...
-      echo -e "section_start:`date +%s`:openosc_clean_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=1 cleanup ...\033[0m" || true
-    - |
-      # Start of OpenOSC Clang MM=1 test ...
-      echo -e "section_start:`date +%s`:openosc_clang1test_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=1 Test ...\033[0m" || true
-    - stdbuf -o L ./build/bin/sirexample
-    - stdbuf -o L ./build/bin/sirtests
-    - stdbuf -o L ./build/bin/sirtests++
-    - |
-      # End of OpenOSC Clang MM=2 test ...
-      echo -e "section_end:`date +%s`:openosc_clang1test_section\r\e[0K" || true
-    - *CheckLogRemnants
-    - make distclean
-    - |
-      # End of cleanup ...
-      echo -e "section_end:`date +%s`:openosc_clean_section\r\e[0K" || true
-    - |
       # Start of OpenOSC Clang MM=2 build ...
-      echo -e "section_start:`date +%s`:openosc_Clang2_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=2 build ...\033[0m" || true
+      echo -e "section_start:`date +%s`:openosc_clang2_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=2 build ...\033[0m" || true
     - export CC="clang"
     - export CXX="clang++"
     - export CFLAGS="-DOPENOSC_MM=2"
@@ -3280,8 +3316,11 @@ OpenOSC (Clang):
     - make tests++ OPENOSC=1
     - |
       # End of OpenOSC Clang MM=2 build ...
-      echo -e "section_end:`date +%s`:openosc_Clang2_section\r\e[0K" || true
+      echo -e "section_end:`date +%s`:openosc_clang2_section\r\e[0K" || true
     - *BuildInformation
+    - |
+      # Start of cleanup ...
+      echo -e "section_start:`date +%s`:openosc_clean_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=2 cleanup ...\033[0m" || true
     - |
       # Start of OpenOSC Clang MM=2 test ...
       echo -e "section_start:`date +%s`:openosc_clang2test_section[collapsed=true]\r\e[0K\033[0;36mOpenOSC Clang MM=2 Test ...\033[0m" || true
